# Allow unstable
unstable_features = true

# Configuring imports
imports_granularity = "Module"
imports_layout = "Mixed"
reorder_imports = false
group_imports = "One"

# Lengths
max_width = 120
chain_width = 120
fn_call_width = 120
comment_width = 80
wrap_comments = true

# Tabs
tab_spaces = 3
hard_tabs = false

# Misc
format_code_in_doc_comments = true
trailing_comma = "Never"
